openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0
  description: |
    A generic REST API example demonstrating common patterns.

    This API uses JSON for request/response bodies and Bearer token authentication.

servers:
  - url: https://api.example.com/v1
    description: Production
  - url: https://api.staging.example.com/v1
    description: Staging

tags:
  - name: Authentication
    description: User authentication endpoints
  - name: Users
    description: User management
  - name: Items
    description: CRUD operations for items

paths:
  /auth/login:
    post:
      operationId: login
      tags: [Authentication]
      summary: Authenticate user
      description: Authenticate with email and password. Returns a JWT access token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
            example:
              email: user@example.com
              password: secretpassword
      responses:
        "200":
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_in:
                    type: integer
              example:
                access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                expires_in: 3600
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/logout:
    post:
      operationId: logout
      tags: [Authentication]
      summary: End session
      description: Invalidate the current access token.
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Successfully logged out
        "401":
          description: Not authenticated

  /users/me:
    get:
      operationId: getCurrentUser
      tags: [Users]
      summary: Get current user
      description: Retrieve the profile of the authenticated user.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Not authenticated

    patch:
      operationId: updateCurrentUser
      tags: [Users]
      summary: Update current user
      description: Update the authenticated user's profile.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                avatar_url:
                  type: string
                  format: uri
      responses:
        "200":
          description: Updated user profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid request body

  /users/{user_id}:
    get:
      operationId: getUser
      tags: [Users]
      summary: Get user by ID
      description: Retrieve a user's public profile.
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: User profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found

  /items:
    get:
      operationId: listItems
      tags: [Items]
      summary: List items
      description: Retrieve a paginated list of items.
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          description: Maximum results to return
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: cursor
          in: query
          description: Pagination cursor
          schema:
            type: string
        - name: status
          in: query
          description: Filter by status
          schema:
            type: string
            enum: [active, archived, draft]
      responses:
        "200":
          description: List of items
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Item"
                  next_cursor:
                    type: string
                    nullable: true

    post:
      operationId: createItem
      tags: [Items]
      summary: Create item
      description: Create a new item.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                description:
                  type: string
                  maxLength: 500
                tags:
                  type: array
                  items:
                    type: string
      responses:
        "201":
          description: Item created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          description: Invalid request body

  /items/{item_id}:
    parameters:
      - name: item_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      operationId: getItem
      tags: [Items]
      summary: Get item
      description: Retrieve item details.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Item details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          description: Item not found

    patch:
      operationId: updateItem
      tags: [Items]
      summary: Update item
      description: Update item details.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                status:
                  type: string
                  enum: [active, archived, draft]
                tags:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Updated item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          description: Invalid request
        "404":
          description: Item not found

    delete:
      operationId: deleteItem
      tags: [Items]
      summary: Delete item
      description: Permanently delete an item.
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Item deleted
        "404":
          description: Item not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
        name:
          type: string
        avatar_url:
          type: string
          format: uri
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [active, archived, draft]
        tags:
          type: array
          items:
            type: string
        owner_id:
          type: string
          format: uuid
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          additionalProperties: true
          description: Additional error details
