/**
 * Generated version configuration.
 *
 * This file is auto-generated by scripts/generate-versions.ts
 * Do not edit manually.
 *
 * Generated: 2025-12-06T19:52:52.057Z
 */

import type { VersionConfig } from "./versioning";

/**
 * Documentation versions from git tags.
 */
export const DOCS_VERSION_CONFIG: VersionConfig = {
  "current": "main",
  "versions": [
    {
      "tag": "main",
      "name": "Development",
      "slug": "main",
      "isLatest": true
    }
  ]
};

/**
 * Whether to show docs version switcher.
 * Only true when there are multiple versions.
 */
export const SHOW_DOCS_VERSIONS = false;
