#!/usr/bin/env bun
/**
 * Generate version configuration from git tags.
 *
 * This script scans git tags and generates a TypeScript file
 * with version configuration that can be imported client-side.
 *
 * Usage: bun run scripts/generate-versions.ts
 */

import { execSync } from "child_process";
import fs from "fs";
import path from "path";

interface Version {
  tag: string;
  name: string;
  slug: string;
  commit?: string;
  date?: string;
  isLatest: boolean;
}

interface VersionConfig {
  current: string;
  versions: Version[];
}

function parseSemVer(tag: string) {
  const match = tag.match(/^v?(\d+)(?:\.(\d+))?(?:\.(\d+))?$/);
  if (!match) return null;
  return {
    major: parseInt(match[1], 10),
    minor: parseInt(match[2] ?? "0", 10),
    patch: parseInt(match[3] ?? "0", 10),
  };
}

function compareSemVer(a: string, b: string): number {
  const semA = parseSemVer(a);
  const semB = parseSemVer(b);
  if (!semA || !semB) return a.localeCompare(b);

  if (semA.major !== semB.major) return semA.major - semB.major;
  if (semA.minor !== semB.minor) return semA.minor - semB.minor;
  return semA.patch - semB.patch;
}

function formatVersion(tag: string): string {
  const semver = parseSemVer(tag);
  if (!semver) return tag;
  return `v${semver.major}.${semver.minor}.${semver.patch}`;
}

function getGitTags(): Array<{ tag: string; commit: string; date: string }> {
  try {
    const output = execSync(
      'git tag -l "v*" --format="%(refname:short)|%(objectname:short)|%(creatordate:iso8601)"',
      { encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] }
    );

    return output
      .trim()
      .split("\n")
      .filter(Boolean)
      .map((line) => {
        const [tag, commit, date] = line.split("|");
        return { tag, commit, date: date?.split(" ")[0] ?? "" };
      })
      .filter((info) => parseSemVer(info.tag) !== null);
  } catch {
    return [];
  }
}

function generateDocsVersionConfig(): VersionConfig {
  const tags = getGitTags();

  if (tags.length === 0) {
    return {
      current: "main",
      versions: [
        {
          tag: "main",
          name: "Development",
          slug: "main",
          isLatest: true,
        },
      ],
    };
  }

  const sorted = [...tags].sort((a, b) => compareSemVer(b.tag, a.tag));
  const latestTag = sorted[0].tag;

  const versions: Version[] = sorted.map((info) => ({
    tag: info.tag,
    name: formatVersion(info.tag),
    slug: info.tag.startsWith("v") ? info.tag : `v${info.tag}`,
    commit: info.commit,
    date: info.date,
    isLatest: info.tag === latestTag,
  }));

  return { current: latestTag, versions };
}

function main() {
  const config = generateDocsVersionConfig();
  const showVersions = config.versions.length > 1;

  const output = `/**
 * Generated version configuration.
 *
 * This file is auto-generated by scripts/generate-versions.ts
 * Do not edit manually.
 *
 * Generated: ${new Date().toISOString()}
 */

import type { VersionConfig } from "./versioning";

/**
 * Documentation versions from git tags.
 */
export const DOCS_VERSION_CONFIG: VersionConfig = ${JSON.stringify(
    config,
    null,
    2
  )};

/**
 * Whether to show docs version switcher.
 * Only true when there are multiple versions.
 */
export const SHOW_DOCS_VERSIONS = ${showVersions};
`;

  const outputPath = path.join(process.cwd(), "lib", "versions.generated.ts");
  fs.writeFileSync(outputPath, output, "utf-8");

  console.log(`Generated ${outputPath}`);
  console.log(`  Versions: ${config.versions.length}`);
  console.log(`  Current: ${config.current}`);
  console.log(`  Show switcher: ${showVersions}`);
}

main();
